### ISSUE TITLE
Z-index 1 and 2 overlaying Z-index 100 for hamburger menu

### ISSUE THREAD

**Issue by j10czar** [a1exanderklein/ACM-Website#32]
<img width="1543" alt="Screenshot 2024-04-11 at 1 53 10 PM" src="https://github.com/a1exanderklein/ACM-Website/assets/104178704/e799324b-5c8f-453f-bb64-e119bfcce6be">

**Comment by alexgklein** [comment]
#37  carousel overlay, still need sigs.

**Comment by alexgklein** [comment]
Both are fixed
